---
- hosts:              docker_swarm_manager
  vars:
    http_port:        80
    max_clients:      200
  remote_user:        root
  tasks:
    # - name:           Init Swarm Manager
    #   shell: "docker swarm leave --force"
    - name:           Init Swarm Manager
      shell: "docker swarm init --advertise-addr {{ansible_host}} || echo 1"
    - name:           Swarm Token to file /worker.tkn
      shell: "docker swarm join-token -q  worker > /worker.tkn"
    - name:           Swarm Token to file /manager.tkn
      shell: "docker swarm join-token -q  manager > /manager.tkn"

    - name:           Copy Swarm worker Tokens
      fetch:
        src:          /worker.tkn
        flat: true
        dest:         ../tokens/{{ansible_host}}/worker.tkn

    - name:           Copy Swarm manager Tokens
      fetch:
        src:          /manager.tkn
        flat: true
        dest:         ../tokens/{{ansible_host}}/manager.tkn
