---
- hosts:
    - all
  vars:
    http_port:        80
    max_clients:      200
  remote_user:        root
  tasks:
    # - name:         REMOVE ERRORS
    #   command:      add-apt-repository --remove "deb [arch=amd64] https://download.docker.com/linux/ubuntu $$(lsb_release -cs) stable"
    #
    # - name:         REMOVE ERRORS
    #   command:      add-apt-repository --remove "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: Ensure hostname set
      hostname: name={{ inventory_hostname }}
      when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

    - name:           write  ansible_hostname to /hostname
      copy:
        content:      "{{ ansible_hostname }}"
        dest:         /hostname

    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    - name:           Install Docker prerequisites on Ubuntu xenial
      apt:
        update_cache: yes
        pkg:          "{{ item }}"
        state:        latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - unzip

    - name:           IPTABLES
      shell:          |
        iptables -A INPUT -p tcp -m tcp --dport 9323 -j ACCEPT
        iptables -A INPUT -p tcp -m tcp --dport 7946 -j ACCEPT
        iptables -A INPUT -p udp -m udp --dport 7946 -j ACCEPT
        iptables -A INPUT -p tcp -m tcp --dport 4789 -j ACCEPT
        iptables -A INPUT -p 50 -j ACCEPT

    - name:           Install Docker key on Ubuntu
      apt_key:
        url:          "https://download.docker.com/linux/ubuntu/gpg"

    - name:           Install Docker repository on Ubuntu xenial
      apt_repository:
        repo:         deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state:        present

    - name:           Install Docker packages on Ubuntu xenial
      apt:
        pkg:          "docker-ce"
        state:        latest
        update_cache: yes

    - name:           Copy Docker Service Config /etc/docker/daemon.json
      copy:
        src:          ../config/docker_daemon.json
        dest:         /etc/docker/daemon.json
        owner:        root

    # - name:         Stop Docker Service
    #   service:
    #     name:       docker
    #     state:      stopped
    #
    # - name:           set DOCKER_OPTS in  /etc/default/docker
    #   when: DOCKER_OPTS is defined
    #   copy:
    #     content:      |
    #       DOCKER_OPTS="{{ DOCKER_OPTS }}"
    #     dest:         /etc/default/docker

    - name:           Start Docker Service
      service:
        name:         docker
        state:        started


    - name: Creates directory /data/elasticsearch
      file: path=/data/elasticsearch state=directory

    - name: Creates directory /data/portainer
      file: path=/data/portainer state=directory

    - name: Creates directory /data/aerospike
      file: path=/data/aerospike state=directory

    - name: Creates directory /data/grafana
      file: path=/data/grafana state=directory

    - name: Creates directory /data/influx
      file: path=/data/influx state=directory
