version:                                 '3.7'
services:
  couchbase_master:
    image:                               couchbase/server:community-5.1.1
    ports:
      - 8091:8091
    command:                             bash -c "echo \"$$configureScript\" > /opt/couchbase/configure.sh ;  bash /opt/couchbase/configure.sh "
    networks:
     - couchbase
    deploy:
      replicas:                          1
      resources:
       limits:
         cpus:                           '1'
         memory:                         1000M
    environment:
       configureScript:                  |-
          set -m
          set -x
          /entrypoint.sh couchbase-server &

          until $$(curl  -u Administrator:password  --output /dev/null --silent --head --fail http://0.0.0.0:8091/pools); do
              printf '.'
              sleep 1
          done

          couchbase-cli cluster-init -c 0.0.0.0 --cluster-username Administrator \
           --cluster-password password --services data,index,query,fts \
           --cluster-ramsize 2048 --cluster-index-ramsize 1024 \
           --cluster-fts-ramsize 1024 --index-storage-setting default \

          # Setup index and memory quota
          curl -v -X POST http://0.0.0.0:8091/pools/default -d memoryQuota=300 -d indexMemoryQuota=300

          # Setup services
          curl -v http://0.0.0.0:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex%2Cfts

          # Setup credentials
          curl -v http://0.0.0.0:8091/settings/web -d port=8091 -d username=Administrator -d password=password

          # Setup Memory Optimized Indexes
          curl -i -u Administrator:password -X POST http://0.0.0.0:8091/settings/indexes -d 'storageMode=forestdb'


          fg 1

  couchbase:
    image:                               couchbase/server:community-5.1.1
    command:                             bash -c "echo \"$$configureScript\" > /opt/couchbase/configure.sh ;  bash /opt/couchbase/configure.sh "
    networks:
     - couchbase
    deploy:
      replicas:                          4
      resources:
       limits:
         cpus:                           '1'
         memory:                         1000M
    environment:
       configureScript:                  |-
          set -m
          set -x
          /entrypoint.sh couchbase-server &

          until $$(curl  -u Administrator:password --output /dev/null --silent --head --fail http://0.0.0.0:8091/pools); do
              printf '.'
              sleep 1
          done

          # Setup index and memory quota
          curl -v -X POST http://0.0.0.0:8091/pools/default -d memoryQuota=300 -d indexMemoryQuota=300

          # Setup services
          curl -v http://0.0.0.0:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex%2Cfts

          # Setup credentials
          curl -v http://0.0.0.0:8091/settings/web -d port=8091 -d username=Administrator -d password=password

          # Setup Memory Optimized Indexes
          curl -i -u Administrator:password -X POST http://0.0.0.0:8091/settings/indexes -d 'storageMode=forestdb'

          sleep 15
          until $$(curl  -u Administrator:password  --output /dev/null --silent --head --fail http://couchbase_master:8091/pools); do
              printf '.'
              sleep 1
          done

          IP=`hostname -I | cut -d ' ' -f1`
          echo "IP: " $$IP

          # couchbase-cli server-add -c=couchbase_master:8091  -u Administrator -p password --server-add-username=Administrator --server-add-password=password --server-add=$$IP  --services=data,index,query,fts
          # couchbase-cli rebalance -c=couchbase_master:8091  -u Administrator -p password

          couchbase-cli server-add -c couchbase_master:8091 --username Administrator --password password --server-add $$IP --server-add-username Administrator --server-add-password password --services data,index,query,fts
          couchbase-cli rebalance -c=couchbase_master:8091  -u Administrator -p password

          fg 1

networks:
  couchbase:
    driver:                              overlay
    attachable: true
    # ip-range: 172.16.238.0/24
