version:                  '3.2'

services:
   fakesmtp:
     logging:
       driver: none
     image:               giorgiocasciaro/civil-microservices-fakesmtp:6
     ports:
       - 8025:8025
     networks:
       - microservicesNet

networks:
  microservicesNet:
    driver:               bridge
