version:                                 '3.3'
services:
  couchbase_nodes:
    image:                               couchbase/server:community-5.0.0
    ports:
      - 8091:8091
    command:                             bash -c "echo \"$$configureScript\" > /opt/couchbase/configure.sh ;  bash /opt/couchbase/configure.sh "
    networks:
     microservicesNet:
       aliases:
          - couchbase.nodeid1
    volumes:
       - ../../couchbase/gitignore/nodeid1:/opt/couchbase/var
    deploy:
      mode:                              global
      update_config:
        parallelism: 1
        delay: 30s
                                 global
    environment:
       COUCHBASE_ADMINISTRATOR_USERNAME: Administrator
       COUCHBASE_ADMINISTRATOR_PASSWORD: password
       COUCHBASE_BUCKET:                 default
       COUCHBASE_BUCKET_PASSWORD:
       configureScript:                  |-
          set -m
          set -x
          /entrypoint.sh couchbase-server &
          #CHECK IF CLUSTER EXIST
          response=$$(curl --fail -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://couchbase_nodes:8091/pools)
          echo $$response

          sleep 15
          curl -v http://0.0.0.0:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex%2Cfts
          curl -v http://0.0.0.0:8091/settings/web -d port=8091 -d username=$$COUCHBASE_ADMINISTRATOR_USERNAME -d password=$$COUCHBASE_ADMINISTRATOR_PASSWORD
          curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/pools/default -d memoryQuota=1512 -d indexMemoryQuota=1512 -d ftsMemoryQuota=1512
          curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/nodes/self/controller/settings  -d data_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fdata  -d index_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Findexdata
          curl  -X POST -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/settings/indexes  -d 'storageMode=forestdb'
          if [ "$$response" == "" ]; then
            echo "CLUCTER NOT ACTIVE - FIRST NODE"
            couchbase-cli node-init  --cluster=couchbase_nodes:8091 -u $$COUCHBASE_ADMINISTRATOR_USERNAME -p $$COUCHBASE_ADMINISTRATOR_PASSWORD --node-init-hostname couchbase.nodeid1
            couchbase-cli cluster-init --cluster=couchbase_nodes:8091 --cluster-username $$COUCHBASE_ADMINISTRATOR_USERNAME --cluster-password $$COUCHBASE_ADMINISTRATOR_PASSWORD --cluster-name civil-connect --services=data,index,query,fts
            curl  -X POST -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/settings/indexes  -d 'storageMode=forestdb'
          else
            echo "CLUCTER ACTIVE - NOT FIRST NODE"
            curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://couchbase_nodes:8091/controller/addNode -d "hostname=couchbase.nodeid1&user=$$COUCHBASE_ADMINISTRATOR_USERNAME&password=$$COUCHBASE_ADMINISTRATOR_PASSWORD&services=kv%2Cn1ql%2Cindex%2Cfts"
            couchbase-cli rebalance --cluster=couchbase_nodes:8091 --user Administrator --password password
          fi;
          fg 1

  couchbase_test_node:
    image:                               couchbase/server:community-5.0.0
    command:                             bash -c "echo \"$$configureScript\" > /opt/couchbase/configure.sh ;  bash /opt/couchbase/configure.sh "
    networks:
     microservicesNet:
       aliases:
          - couchbase.nodeid2
    volumes:
       - ../../couchbase/gitignore/nodeid2:/opt/couchbase/var
    environment:
       COUCHBASE_ADMINISTRATOR_USERNAME: Administrator
       COUCHBASE_ADMINISTRATOR_PASSWORD: password
       COUCHBASE_BUCKET:                 default
       COUCHBASE_BUCKET_PASSWORD:
       configureScript:                  |-
          # SIMULATE DEPLOY DELAY
          sleep 15

          set -m
          set -x
          /entrypoint.sh couchbase-server &
          #CHECK IF CLUSTER EXIST
          response=$$(curl --fail -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://couchbase_nodes:8091/pools)
          echo $$response

          sleep 15
          curl -v http://0.0.0.0:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex%2Cfts
          curl -v http://0.0.0.0:8091/settings/web -d port=8091 -d username=$$COUCHBASE_ADMINISTRATOR_USERNAME -d password=$$COUCHBASE_ADMINISTRATOR_PASSWORD
          curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/pools/default -d memoryQuota=1512 -d indexMemoryQuota=1512 -d ftsMemoryQuota=1512
          curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/nodes/self/controller/settings  -d data_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fdata  -d index_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Findexdata
          curl  -X POST -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/settings/indexes  -d 'storageMode=forestdb'
          if [ "$$response" == "" ]; then
            echo "CLUCTER NOT ACTIVE - FIRST NODE"
            couchbase-cli node-init  --cluster=couchbase_nodes:8091 -u $$COUCHBASE_ADMINISTRATOR_USERNAME -p $$COUCHBASE_ADMINISTRATOR_PASSWORD --node-init-hostname couchbase.nodeid2
            couchbase-cli cluster-init --cluster=couchbase_nodes:8091 --cluster-username $$COUCHBASE_ADMINISTRATOR_USERNAME --cluster-password $$COUCHBASE_ADMINISTRATOR_PASSWORD --cluster-name civil-connect --services=data,index,query,fts
            curl  -X POST -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://0.0.0.0:8091/settings/indexes  -d 'storageMode=forestdb'
          else
            echo "CLUCTER ACTIVE - NOT FIRST NODE"
            curl -v  -u $$COUCHBASE_ADMINISTRATOR_USERNAME:$$COUCHBASE_ADMINISTRATOR_PASSWORD http://couchbase_nodes:8091/controller/addNode -d "hostname=couchbase.nodeid2&user=$$COUCHBASE_ADMINISTRATOR_USERNAME&password=$$COUCHBASE_ADMINISTRATOR_PASSWORD&services=kv%2Cn1ql%2Cindex%2Cfts"
            couchbase-cli rebalance --cluster=couchbase_nodes:8091 --user Administrator --password password
          fi;
          fg 1
networks:
  microservicesNet:
    driver:                              bridge


#/opt/couchbase/var/lib/couchbase/data
#/opt/couchbase/var/lib/couchbase/data
