version: '3.2'

services:
   aerospike:
    #  logging:
    #    driver: none
     image: giorgiocasciaro/civil-microservices-aerospike:7
     command: bash -c "echo \"$$AEROSPIKE_CONF\" > /etc/aerospike/aerospike.conf ; cat /etc/aerospike/aerospike.conf ; asd --foreground "
     volumes:
       - ../gitignore/data:/opt/aerospike/data
       - ../gitignore/smd:/opt/aerospike/smd
       - ../gitignore/usr:/opt/aerospike/usr/udf/lua
     networks:
       - aerospike
     environment:
       AEROSPIKE_CONF: |-
          service {
          		node-id-interface eth0
          }
          mod-lua {
            cache-enabled false
          }
          logging {
            console {
              context any warning
              context ldt warning
              context udf info
              context query warning
            }
          }
          network {
          	service {
          		address eth0
          		port 3000
          		access-address eth0 virtual

          	}
            heartbeat {
               mode multicast
               multicast-group 239.0.0.1
               port 3002
             }

          	fabric {
          		port 3001
          	}

          	info {
          		port 3003
          	}
          }

          namespace cc_tests {
          	replication-factor 1
          	memory-size 100M
          	storage-engine device {
          		file /opt/aerospike/data/cc_tests.dat
          		filesize 100M
          	}
          }

          namespace cc_schema {
          	replication-factor 1
          	memory-size 100M
          	storage-engine device {
          		file /opt/aerospike/data/cc_schema.dat
          		filesize 100M
          	}
          }

          namespace cc_users {
          	replication-factor 1
          	memory-size 100M
          	storage-engine device {
          		file /opt/aerospike/data/cc_users.dat
          		filesize 100M
          	}
          }

          namespace cc_dashboards {
          	replication-factor 1
          	memory-size 100M
          	storage-engine device {
          		file /opt/aerospike/data/cc_dashboards.dat
          		filesize 100M
          	}
          }


networks:
  aerospike:
    driver: bridge
